### ISSUE TITLE
Maybe typo

### ISSUE THREAD

**Issue by Jacob-Zhou** [KiroSummer/LinearModel#1]
https://github.com/KiroSummer/LinearModel/blob/c52f083377f8c1b3cbed1a5085e4379b02f75bae/LM/LM.py#L101

Perhaps `f.append("15:" + str(tag) + "*" + sentence.word[pos][-(i + 1)::])` ?

**Comment by KiroSummer** [comment]
@Jacob-Zhou Yes, you are right. It's my mistake.
